# 配置文件

DAILY_TIME: "16:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-07-11" # 纪念日
CITY: "伊犁哈萨克自治州"

BIRTHDAY:
  - "03-31"

APP_ID: "wx547817f784d10386"
APP_SECRET: "96189f4e68f1dfba84ba9293cd7a90ec"

USER_ID: 
  - "ouUHL6e2W5nHAcRK_NHjPFBG_qEY"
TEMPLATE_ID: "G9vGjc11aSqjHYxRNnGZYeYoWJz-kq8WC7Y6AAZJMZY	"
